-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 18:43:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema music_collection
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `music_collection` ;

-- -----------------------------------------------------
-- Schema music_collection
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_collection` DEFAULT CHARACTER SET utf8 ;
USE `music_collection` ;

-- -----------------------------------------------------
-- Table `music_collection`.`artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_collection`.`artists` ;

CREATE TABLE IF NOT EXISTS `music_collection`.`artists` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Artist or band identificator.',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'Name of the artist or band.',
  `year` INT(4) NULL COMMENT 'Year of foundation.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_collection`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_collection`.`members` ;

CREATE TABLE IF NOT EXISTS `music_collection`.`members` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'People identificator.',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'Full name of the person.',
  `role` VARCHAR(50) NULL COMMENT 'Member role on the band.',
  `artist_id` INT UNSIGNED NULL COMMENT 'Artist or band identificator.',
  PRIMARY KEY (`id`),
  INDEX `members_fk_artists_1_idx` (`artist_id` ASC),
  CONSTRAINT `members_fk_artists_1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_collection`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_collection`.`styles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_collection`.`styles` ;

CREATE TABLE IF NOT EXISTS `music_collection`.`styles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Style identificator.',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'Style name.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_collection`.`artists_styles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_collection`.`artists_styles` ;

CREATE TABLE IF NOT EXISTS `music_collection`.`artists_styles` (
  `artist_id` INT UNSIGNED NOT NULL COMMENT 'Name of the artist or band.',
  `style_id` INT UNSIGNED NOT NULL COMMENT 'Style identificator.',
  PRIMARY KEY (`artist_id`, `style_id`),
  INDEX `artists_styles_fk_styles_1_idx` (`style_id` ASC),
  INDEX `artists_styles_fk_artists_1_idx` (`artist_id` ASC),
  CONSTRAINT `artists_styles_fk_artists_1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_collection`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artists_styles_fk_styles_1`
    FOREIGN KEY (`style_id`)
    REFERENCES `music_collection`.`styles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_collection`.`related_artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_collection`.`related_artists` ;

CREATE TABLE IF NOT EXISTS `music_collection`.`related_artists` (
  `artist_id` INT UNSIGNED NOT NULL COMMENT 'Name of the artist or band.',
  `related_artist_id` INT UNSIGNED NOT NULL COMMENT 'Name of the artist or band related to.',
  PRIMARY KEY (`artist_id`, `related_artist_id`),
  INDEX `related_artists_fk_artists_2_idx` (`related_artist_id` ASC),
  INDEX `related_artists_fk_artists_1_idx` (`artist_id` ASC),
  CONSTRAINT `related_artists_fk_artists_1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_collection`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `related_artists_fk_artists_2`
    FOREIGN KEY (`related_artist_id`)
    REFERENCES `music_collection`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;